name: nerf-camera-tools
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - scipy
  - matplotlib
  - pip
  - pip:
      - configargparse
      - opencv-contrib-python
      - imageio
      - imageio-ffmpeg
      - tqdm
